### ISSUE TITLE
request for 2.3 version image

### ISSUE THREAD

**Issue by jeff-knurek** [mroth/scalafmt-docker#1]
Would be nice to keep the version aligned with what's available in the `scalafmt-native` image
https://hub.docker.com/r/mrothy/scalafmt-native/tags?page=1&name=2.3

thanks

**Comment by mroth** [comment]
Hi @jeff-knurek -- I hadn't been keeping this up to date since it's only purpose (for me) was during the period that scalafmt-native was unbuildable, which was fixed since the 2.3.x builds of scalafmt. Since the native version boot orders of magnitude faster and is significantly smaller image than the JVM version, I didn't see a reason for an independent containerized JVM version.

That said, it's trivial to update, so I'll do so now -- but if you could let me know your use case for preferring the JVM version, my curiosity would appreciate it!

**Comment by jeff-knurek** [comment]
I'm trying to build a CircleCI orb https://circleci.com/docs/2.0/orb-intro/ to run scalafmt and CircleCI requires the executing image to have shell dir:
```
Build image is not supported. Please check that it contains a shell and /bin directory.
```
so, it's not that the JVM is needed, but something more than `scratch` image is.

If you could create an alpine based image off the same process of the existing `scalafmt-native` image that'd be great!

**Comment by mroth** [comment]
@jeff-knurek Ahh gotcha. It's kind of an edge case I don't want to maintain a separate image for, BUT, it's super easy to make a "downstream" image of Alpine that just contains the binary.  Basically, you just need a Dockerfile such as:

```dockerfile
FROM mrothy/scalafmt-native:latest as native

FROM alpine:latest
COPY --from=native /app/scalafmt /usr/local/bin/scalafmt
```

This makes a "multistage" build in Docker, but the first stage does nothing really, and the second stage just copies the scalafmt-native binary to somewhere in PATH on a raw Alpine image.  Tested this and it builds in a fraction of a second for me. If desired, you can add more commands in the second stage if you want to add additional requirements to the image (such as `RUN apk add git` for example).

Once you have that, you can just drop it in a repo and set up an "automated build" in Docker Hub:
https://docs.docker.com/docker-hub/builds/

You can even configure the Docker Hub automatic build to automatically re-build if the upstream image changes (change "Repository Links" to "Enable for Base Image") and your image will be automatically rebuilt every time my base image is updated.

Does that help?
